### ISSUE TITLE
承認された時にGitHubにイシューを展開する

### ISSUE THREAD

**Issue by KisaragiEffective** [Lucky3028/IdeaDiscussionMaster#41]
見てて大変そう。今回は特に

**Comment by Lucky3028** [comment]
SeichiAssistではないものとかそもそもIssueにする必要がないものもあるんですよね（開発に関係ないもの）
それの扱いをどうするか

**Comment by KisaragiEffective** [comment]
手動でコマンドうつで良いのでは
例: `\ghissue 12345` => `https://redmine.seichi.click/issues/12345 にて承認された。`
みたいな
タイトルつけるぐらいはやります

**Comment by Lucky3028** [comment]
あーなるほど、複数指定可にすればそれでいいっすね
